### ISSUE TITLE
Behavior for "Update Variable" and "Variable Synonym"?

### ISSUE THREAD

**Issue by elserj** [Planteome/Ontology-Variable-Request-App#28]
The box for "Search and Select a Variable" for these 2 operations is greyed out until an ontology is chosen, which is fine, but we thought from the verbiage that terms would be dynamically searched when typing in this box.

Unless I'm missing something, there doesn't seem to be a way to actually search at all for existing terms. If this is to be expected, maybe the text should be changed to make this clearer?

Thanks

**Comment by elserj** [comment]
We have discovered that this behavior is caused by a lack of a release for different ontologies. Once a release is done, autocomplete works.

Apparently we just need to do a release for each CO.

**Comment by cooperl09** [comment]
I did the release process for wheat repo but its still not working.  Is it looking for the obo file with out the crop name? @marieALaporte did a release for rice and its not working either.

**Comment by elserj** [comment]
I'm not sure, when I do the "deploy" step, there is a spot to specify the "master obo" file, and I used the withcropname files, because at least for wheat, it's the only one.

**Comment by elserj** [comment]
I think we figured this out, that the release needs to be a "Full release" not a "PreRelease".
