### ISSUE TITLE
form is not working

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/Ontology-Variable-Request-App#45]
I was doing a training today on how to use the form, and the 'internal server error' is back. At least for https://trait-requests.planteome.org/

**Comment by marieALaporte** [comment]
FYI, the rtbbase one does not work anymore now

**Comment by nmenda** [comment]
@marieALaporte you probably need to do a git pull. Thre was a commit a couple of weeks ago to fix this

**Comment by marieALaporte** [comment]
yes, it worked for a period of time, but now the 'internal server error' is back

**Comment by nmenda** [comment]
ok I see the same with submit.rtbbase.org
It looks like an issue with  creating the label in github

`return 'Could not create Label\nResponse:'+r.content, 500
TypeError: must be str, not bytes
Tue Mar 16 12:58:05 2021 {'REMOTE_ADDR': '::ffff:127.0.0.1', 'REMOTE_PORT': '41216', 'HTTP_HOST': 'localhost:5000', (hidden keys: 32)} failed with TypeError
`

**Comment by elserj** [comment]
I was trying to work on this and I restarted the service, and now it appears to be working again. Can you restart the rtbbase one and see if it fixes it for you as well? @nmenda

**Comment by marieALaporte** [comment]
thanks @elserj. I am doing a second round of a training tomorrow morning, so I let you know if we run into more issues

**Comment by nmenda** [comment]
@elserj restarting worked. Thanks!
